# Generated by Django 6.0.6 on 2026-08-04 15:42

import backyardchirps.features.detections.entity
import backyardchirps.models.stored_detection
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'app setting',
            },
        ),
        migrations.CreateModel(
            name='DetectedSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'detected species',
                'db_table': 'birds_recorder_species',
            },
        ),
        migrations.CreateModel(
            name='StoredDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('confidence', models.FloatField()),
                ('clip_path', models.CharField(blank=True, max_length=500, null=True)),
                ('clip_duration_seconds', models.FloatField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=backyardchirps.models.stored_detection.validation_status_choices, default=backyardchirps.features.detections.entity.ValidationStatus['AUTO_CONFIRMED'], max_length=20)),
                ('original_confidence', models.FloatField(blank=True, null=True)),
                ('analysis_time_ms', models.IntegerField(blank=True, null=True)),
                ('analysis_candidates', models.JSONField(blank=True, null=True)),
                ('original_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_detections', to='birds_recorder.detectedspecies')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='birds_recorder.detectedspecies')),
            ],
            options={
                'db_table': 'birds_recorder_detection',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StoredSpeciesOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_confirm_threshold', models.FloatField(blank=True, null=True)),
                ('blacklisted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override', to='birds_recorder.detectedspecies')),
            ],
            options={
                'verbose_name': 'species override',
            },
        ),
    ]
