# Generated by Django 6.0.8 on 2026-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds_recorder', '0004_drop_xeno_canto_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUpdateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'update check',
            },
        ),
    ]
