# Generated by Django 6.0.8 on 2026-08-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds_recorder', '0005_storedupdatecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'update request',
            },
        ),
    ]
